### ISSUE TITLE
Copy Module Across Projects

### ISSUE THREAD

**Issue by relshire** [biosistemika/scinote-web#11]
Many lab work flows reuse protocols across projects. With V 1.0.0 we can clone modules within projects but not copy between. This results in a huge time sink (and potential errors) re-entering the same protocols. It seems to me that replicating protocols should be a basic function of an electronic lab book. It is possible that this functionality exists in scinote, but I could not figure out how to do it and there is no documentation (see issue  #4  ). 

This is a feature request.
This is critical

**Comment by Ducz0r** [comment]
Hey @relshire,

Firstly let me thank you for contacting us. Sadly, protocol management (e.g. exporting, importing, cloning protocols) is not currently possible in sciNote.

However, it is planned (almost finished actually) for the next release of sciNote, 1.1. We plan to release it by the end of next month.

**Comment by relshire** [comment]
Hey @Ducz0r,

Thanks for this very informative response. I'll be looking forward to version 1.1 later this month.

--Rob
