### ISSUE TITLE
rake db:reset failed

### ISSUE THREAD

**Issue by umardraz** [biosistemika/scinote-web#12]
Hello would you please help me what is that and how I can fix ?

scinote@82dad78f0ac9:/usr/src/app$ rake db:reset
rake aborted!
NoMethodError: undefined method `reject' for #<String:0x00560904ca2b88>
/usr/local/bundle/gems/figaro-1.1.1/lib/figaro/application.rb:64:in `global_configuration'
/usr/local/bundle/gems/figaro-1.1.1/lib/figaro/application.rb:32:in `configuration'
/usr/local/bundle/gems/figaro-1.1.1/lib/figaro/application.rb:42:in `each'
/usr/local/bundle/gems/figaro-1.1.1/lib/figaro/application.rb:36:in `load'
/usr/local/bundle/gems/figaro-1.1.1/lib/figaro.rb:23:in `load'
/usr/local/bundle/gems/figaro-1.1.1/lib/figaro/rails/railtie.rb:5:in `block in <class:Railtie>'
/usr/local/bundle/gems/activesupport-4.2.5/lib/active_support/lazy_load_hooks.rb:36:in `call'
/usr/local/bundle/gems/activesupport-4.2.5/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
/usr/local/bundle/gems/activesupport-4.2.5/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
/usr/local/bundle/gems/activesupport-4.2.5/lib/active_support/lazy_load_hooks.rb:44:in `each'
/usr/local/bundle/gems/activesupport-4.2.5/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
/usr/local/bundle/gems/railties-4.2.5/lib/rails/application.rb:148:in `run_load_hooks!'
/usr/local/bundle/gems/railties-4.2.5/lib/rails/application.rb:96:in `instance'
/usr/local/bundle/gems/railties-4.2.5/lib/rails/railtie.rb:123:in `config'
/usr/src/app/config/application.rb:23:in `<class:Application>'
/usr/src/app/config/application.rb:10:in `<module:Scinote>'
/usr/src/app/config/application.rb:9:in `<top (required)>'
/usr/src/app/Rakefile:4:in `require'
/usr/src/app/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)
scinote@82dad78f0ac9:/usr/src/app$

Br.

Umar

**Comment by jbargu** [comment]
My guess would be an error in `application.yml`. Figaro gem tries to read it but something goes wrong (probably something related with database). Do you mind sharing it?

**Comment by umardraz** [comment]
SECRET_KEY_BASE='45uvhvhabcdef'
PAPERCLIP_STORAGE='filesystem'
MAIL_FROM='support@myexample.net'
MAIL_REPLYTO='support@myexample.net'
SMTP_ADDRESS='localhost'
SMTP_PORT=25
SMTP_DOMAIN='myexample.net'
PAPERCLIP_HASH_SECRET='45uvhvhabcdef'
ENABLE_TUTORIAL=true

**Comment by jbargu** [comment]
Try using ":" instead of "=" for separating key/value pair, ie.
`SECRET_KEY_BASE: "45uvhvhabcdef".`

**Comment by umardraz** [comment]
Thanks for your help, now I have new error on make run

root@scinote:~/scinote-web# make run
Starting scinoteweb_dbdata_1
scinoteweb_db_1 is up-to-date
Creating scinoteweb_web_1
Attaching to scinoteweb_dbdata_1, scinoteweb_db_1, scinoteweb_web_1
scinoteweb_dbdata_1 exited with code 0
db_1     | The files belonging to this database system will be owned by user "postgres".
db_1     | This user must also own the server process.
db_1     |
db_1     | The database cluster will be initialized with locale "en_US.utf8".
db_1     | The default database encoding has accordingly been set to "UTF8".
db_1     | The default text search configuration will be set to "english".
db_1     |
db_1     | Data page checksums are disabled.
db_1     |
db_1     | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db_1     | creating subdirectories ... ok
db_1     | selecting default max_connections ... 100
db_1     | selecting default shared_buffers ... 128MB
db_1     | selecting dynamic shared memory implementation ... posix
db_1     | creating configuration files ... ok
db_1     | creating template1 database in /var/lib/postgresql/data/base/1 ... ok
db_1     | initializing pg_authid ... ok
db_1     | initializing dependencies ... ok
db_1     | creating system views ... ok
db_1     | loading system objects' descriptions ... ok
db_1     | creating collations ... ok
db_1     | creating conversions ... ok
db_1     | creating dictionaries ... ok
db_1     | setting privileges on built-in objects ... ok
db_1     | creating information schema ... ok
db_1     | loading PL/pgSQL server-side language ... ok
db_1     | vacuuming database template1 ... ok
db_1     | copying template1 to template0 ... ok
db_1     | copying template1 to postgres ... ok
db_1     | syncing data to disk ... ok
db_1     |
db_1     | Success. You can now start the database server using:
db_1     |
db_1     |     postgres -D /var/lib/postgresql/data
db_1     | or
db_1     |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db_1     |
db_1     |
db_1     | WARNING: enabling "trust" authentication for local connections
db_1     | You can change this by editing pg_hba.conf or using the option -A, or
db_1     | --auth-local and --auth-host, the next time you run initdb.
db_1     | ****************************************************
db_1     | WARNING: No password has been set for the database.
db_1     |          This will allow anyone with access to the
db_1     |          Postgres port to access your database. In
db_1     |          Docker's default configuration, this is
db_1     |          effectively any other container on the same
db_1     |          system.
db_1     |
db_1     |          Use "-e POSTGRES_PASSWORD=password" to set
db_1     |          it in "docker run".
db_1     | ****************************************************
db_1     | waiting for server to start....LOG:  database system was shut down at 2016-06-02 17:44:40 UTC
db_1     | LOG:  MultiXact member wraparound protections are now enabled
db_1     | LOG:  database system is ready to accept connections
db_1     | LOG:  autovacuum launcher started
db_1     |  done
db_1     | server started
db_1     | ALTER ROLE
db_1     |
db_1     |
db_1     | /docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
db_1     |
db_1     | LOG:  received fast shutdown request
db_1     | LOG:  aborting any active transactions
db_1     | waiting for server to shut down....LOG:  autovacuum launcher shutting down
db_1     | LOG:  shutting down
db_1     | LOG:  database system is shut down
db_1     |  done
db_1     | server stopped
db_1     |
db_1     | PostgreSQL init process complete; ready for start up.
db_1     |
db_1     | LOG:  database system was shut down at 2016-06-02 17:44:41 UTC
db_1     | LOG:  MultiXact member wraparound protections are now enabled
db_1     | LOG:  database system is ready to accept connections
db_1     | LOG:  autovacuum launcher started
web_1    | => Booting Puma
web_1    | => Rails 4.2.5 application starting in development on http://0.0.0.0:3000
web_1    | => Run `rails server -h` for more startup options
web_1    | => Ctrl-C to shutdown server
web_1    | Exiting
web_1    | /usr/local/lib/ruby/2.2.0/fileutils.rb:252:in `mkdir': Permission denied @ dir_s_mkdir - /usr/src/app/tmp (Errno::EACCES)
web_1    |      from /usr/local/lib/ruby/2.2.0/fileutils.rb:252:in `fu_mkdir'
web_1    |      from /usr/local/lib/ruby/2.2.0/fileutils.rb:226:in `block (2 levels) in mkdir_p'
web_1    |      from /usr/local/lib/ruby/2.2.0/fileutils.rb:224:in `reverse_each'
web_1    |      from /usr/local/lib/ruby/2.2.0/fileutils.rb:224:in `block in mkdir_p'
web_1    |      from /usr/local/lib/ruby/2.2.0/fileutils.rb:210:in `each'
web_1    |      from /usr/local/lib/ruby/2.2.0/fileutils.rb:210:in `mkdir_p'
web_1    |      from /usr/local/bundle/gems/railties-4.2.5/lib/rails/commands/server.rb:134:in `block in create_tmp_directories'
web_1    |      from /usr/local/bundle/gems/railties-4.2.5/lib/rails/commands/server.rb:133:in `each'
web_1    |      from /usr/local/bundle/gems/railties-4.2.5/lib/rails/commands/server.rb:133:in `create_tmp_directories'
web_1    |      from /usr/local/bundle/gems/railties-4.2.5/lib/rails/commands/server.rb:77:in `start'
web_1    |      from /usr/local/bundle/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:80:in `block in server'
web_1    |      from /usr/local/bundle/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:75:in `tap'
web_1    |      from /usr/local/bundle/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:75:in `server'
web_1    |      from /usr/local/bundle/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
web_1    |      from /usr/local/bundle/gems/railties-4.2.5/lib/rails/commands.rb:17:in `<top (required)>'
web_1    |      from bin/rails:4:in `require'
web_1    |      from bin/rails:4:in `<main>'

**Comment by jbargu** [comment]
You need to run docker as a normal user, which can be achieved by adding your user to `docker` group. See issue #9 for more info.

**Comment by umardraz** [comment]
Hello thanks for your help, Now i need to restart my server here is the docker ps -a output

CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                     PORTS                    NAMES
b08ce1057633        scinoteweb_web      "/bin/sh -c 'rails s "   2 minutes ago       Up 2 minutes               0.0.0.0:3000->3000/tcp   scinoteweb_web_1
45a3e1cbea4a        scinoteweb_web      "/bin/bash"              3 minutes ago       Exited (0) 2 minutes ago                            scinoteweb_web_run_1
a2ba5f9e24de        postgres:9.4        "/docker-entrypoint.s"   3 minutes ago       Up 3 minutes               5432/tcp                 scinoteweb_db_1
8e06eba73a4f        busybox             "true"                   3 minutes ago       Exited (0) 2 minutes ago                            scinoteweb_dbdata_1

Now i want to know when I need to do after my server's restart.

Br.

Umar
