### ISSUE TITLE
Email Notification Error

### ISSUE THREAD

**Issue by umardraz** [biosistemika/scinote-web#14]
Hello I am running a postfix mail server on same linux machine where this scinote's dockers running her is my application.yml

SECRET_KEY_BASE: "45uvhvhabcdef"
PAPERCLIP_STORAGE: "filesystem"
MAIL_FROM: "support@scicloud.net"
MAIL_REPLYTO: "support@scicloud.net"
SMTP_ADDRESS: "172.17.0.1"
SMTP_PORT: "25"
SMTP_DOMAIN: "scicloud.net"
PAPERCLIP_HASH_SECRET: "45uvhvhabcdef"
ENABLE_TUTORIAL: "true"

now the (rake jobs:work) showing me this error. Would you please help me how I can fix

[Worker(host:d23f4311f1e8 pid:22)] Job Devise::Async::Backend::DelayedJob#perform (id=45) FAILED (1 prior attempts) with OpenSSL::SSL::SSLError: hostname "172.17.0.1" does not match the server certificate
E, [2016-06-05T11:00:30.042230 #22] ERROR -- : 2016-06-05T11:00:30+0000: [Worker(host:d23f4311f1e8 pid:22)] Job Devise::Async::Backend::DelayedJob#perform (id=45) FAILED (1 prior attempts) with OpenSSL::SSL::SSLError: hostname "172.17.0.1" does not match the server certificate
D, [2016-06-05T11:00:30.044595 #22] DEBUG -- :    (0.5ms)  BEGIN

Br.

Umar

**Comment by jbargu** [comment]
Googling for error reveals [this solution](http://batsov.com/articles/2012/12/06/dealing-with-ssl-certificate-validation-errors-in-rails/). `development.rb` is located in `config/environments/development.rb`.

**Comment by umardraz** [comment]
Hello jbargu,

Thanks I already had fixed with these settings, anyway thanks for your answer 

Br.

Umar
