### ISSUE TITLE
Export to PDF not including the image

### ISSUE THREAD

**Issue by swambala** [biosistemika/scinote-web#3]
Report Preview
--------------------
![screen shot 2016-02-20 at 1 40 50 pm](https://cloud.githubusercontent.com/assets/855015/13199342/aa9a5f7e-d7d7-11e5-8778-bff3fe357b54.png)

Report Exported to PDF
---------------------------------
![screen shot 2016-02-20 at 1 37 44 pm](https://cloud.githubusercontent.com/assets/855015/13199336/80b6788c-d7d7-11e5-9cfa-ce094abef720.png)

**Comment by jbargu** [comment]
Hmm, strange. It's reproducible. We'll take a look into it. Thank you.

**Comment by jbargu** [comment]
This was fixed in new version.
