### ISSUE TITLE
Error when uploading .py files 

### ISSUE THREAD

**Issue by Cersad** [biosistemika/scinote-web#7]
When trying to upload a *.py file as part of my analysis pipeline...

![image](https://cloud.githubusercontent.com/assets/9045726/14259180/bbf8e0ce-fa73-11e5-9a89-167703a4c242.png)

I get the following error:

![image](https://cloud.githubusercontent.com/assets/9045726/14259224/f839aabe-fa73-11e5-9a63-b4b4ecc6c494.png)

**Comment by jbargu** [comment]
We allow only certain type of files (with matching content) to prevent malicious files from being uploaded. I'm not sure why .py files don't work. We'll take a look at it, thanks!

**Comment by jbargu** [comment]
This was fixed in the new version.
